config/routes.rb
Rails.application.routes.draw do

    
  devise_for :users
  resources :posts do
    member do
        put "like" => "posts#upvote"
        put "unlike" => "posts#downvote"
        end
    resources :comments 
  end

      
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum:5 }
	validates :body, presence: true
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(params[:comment].permit(:name, :body))

      redirect_to post_path(@post)
	end

	 def destroy
	 	@post = Post.find(params[:post_id])
	 	@comment = @post.comments.find(params[:id])
	 	@comment.destroy

	 	redirect_to post_path(@post)
	 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	
    def index
		@posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
	end

	def new
		@post = Post.new
	end

	def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post
    else
    	render 'new'
	end
end

	def show
		@post=Post.find(params[:id])
	end
    
    def edit
    	@post = Post.find(params[:id])
    end

    def update
    	@post = Post.find(params[:id])

    	if @post.update(params[:post].permit(:title, :body, :image))
        redirect_to @post
    else
    	render 'edit'
        end

    end
    def destroy
    	@post = Post.find(params[:id])
    	@post.destroy
    	redirect_to root_path
    end

     def upvote
        @post.upvote_from current_user
        redirect_to posts_path
      end

      def downvote
        @post.downvote_from current_user
        redirect_to posts_path
      end
    
	private

	  def post_params
	  	params.require(:post).permit(:title, :body, :image)
	  end
      
      def find_post
        @post = Post.find(params[:id])
      end
     

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.name %></p>
<p><%= comment.body %></p>
<p><%= time_ago_in_words(comment.created_at) %>Ago</p>

<% if user_signed_in? %>
  <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-trash btn btn-danger' %></p>
  <% end %>

app/views/comments/_form.html.erb
 <%= form_for([@post, @post.comments.build]) do |f| %>
   <p>
     <%= f.label :name, class:'col-sm-2 control-label' %><br>
     <%= f.text_field :name, class:'form-control' %>
   </p>

   <p>
     <%= f.label :body, class:'col-sm-2 control-label' %><br>
     <%= f.text_area :body, class:'form-control', rows: '5' %>
   </p>

   <p>
     <%= button_tag(type: 'submit', class: "btn btn-info") do %> Submit Comment
     <% end %>
   </p>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'ruby.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="navbar-custom ">
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <a><%= link_to "BlogApplication", root_path, class: 'navbar-brand' %></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <% if !user_signed_in? %>
       <li><%= link_to 'User Logins', new_user_session_path %></li>
      <% end %> 
      
      <% if user_signed_in? %>
      <li><%= link_to 'Make Post', new_post_path %></li>
      <li><%= link_to 'Log Out',destroy_user_session_path, method: :delete %></li>
      <% end %>
          </ul>
  </div>
</nav>
  </div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.3.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.3.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />

<!-- Include JS file. -->
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.3.4/js/froala_editor.min.js'></script>
          
Install from NPM
 <script>
      $(function() {
          $('textarea#edit').froalaEditor({
          	inlineMode: false
          })
      });
  </script>


<%= form_for :post, url: posts_path,class:"form-group", html: { multipart: true } do |f| %>

 <% if @post.errors.any?  %>
 <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving </h2>
 <ul>
   <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
 </ul>
 <% end %>
 <p>
 	<%= f.label :title, class:"col-sm-2 control-label" %><nr>
 	<%= f.text_field :title, class: 'form-control' %>
 </p>

 <p>
 	<%= f.label :body, class:"col-sm-2 control-label" %><nr>
 	<%= f.text_area :body, class:'form-control', id: 'edit' %>
 </p>
 <p>
 	<%= f.label :image %><nr>
 	<%= f.file_field :image %>
 </p>
</div>
 <p>
     
     <%= button_tag(type: 'submit', class: "btn btn-primary") do %> Submit Post
     <% end %>
 </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Fix POst</h1>
<div class="jumbotron">
   <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
<div class="row">

<% @posts.each do |post| %>
 <div class="col-sm-6">
   <h2 class="title"><%= link_to post.title, post %> </h2>
   <p><%= truncate(post.body, length:100) %></p>
   <p class="date"><%= time_ago_in_words(post.created_at) %></p>
   <%= image_tag post.image.url(:medium), class: 'img-thumbnail' %><br>
 

     <%= link_to like_post_path(post), class: 'like', method: :put do %>
       <button type="button" class="btn btn-info aria-label="Left Align">
       	<span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
       	<span class="badge"><%= post.get_upvotes.size %></span>
       </button>
     <% end %>

     <%= link_to unlike_post_path(post), class: 'like', method: :put do %>
       <button type="button" class="btn btn-info aria-label="Left Align">
       	<span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
       	<span class="badge"><%= post.get_downvotes.size %></span>
       </button>
       </div>
     <% end %>
 <% end %>
 
 </div>
 </div>

 <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<h1>Make Something</h1>

<%= form_for :post, url: posts_path, html: { multipart: true } do |f| %>

 <p>
 	<%= f.label :title %><nr>
 	<%= f.text_field :title%>
 </p>

 <p>
 	<%= f.label :body %><nr>
 	<%= f.text_area :body%>
 </p>
 <p>
 	<%= f.label :image %><nr>
 	<%= f.file_field :image %>
 </p>

 <p>
     <%= f.submit %>
 </p>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
     <div align="center">
<h1 class="title">
	<%= @post.title %>
</h1>

<p class="date"><em>Submitted <%= time_ago_in_words(@post.created_at) %> ago</p></em>
	<div class="showimages">
<%= image_tag @post.image.url(:medium), class: 'img-thumbnail' %>
    </div>
	
<div class="froala-view">
<p class="body">
 <%= simple_format(@post.body) %>
</p>
</div>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_post_path(@post), class: 'glyphicon glyphicon-edit btn btn-primary' %>
<%= link_to 'Delete', post_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-trash btn btn-danger'  %>
<% end %>
<h2><%= @post.comments.count %>Comments</h2>
<%= render @post.comments %>
<h3>Join Discussion</h3>
<hr>
<%= render "comments/form" %>
</div>
   </div>
	</div>